version: "3.8"

services:
  web:
    build:
      context: ./web
      dockerfile: DockerFile
    env_file:
      - ./web/.env
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge
